//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projektni_centar_proba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obrasac
    {
        public int ID { get; set; }
        public string NazivSkole { get; set; }
        public string AdresaReg { get; set; }
        public string Opstina { get; set; }
        public Nullable<int> PostaBr { get; set; }
        public Nullable<decimal> MatBrSkole { get; set; }
        public Nullable<decimal> PIB { get; set; }
        public Nullable<decimal> BrojRacuna { get; set; }
        public string Web { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string RadnoMes { get; set; }
        public string VrstaTel { get; set; }
        public Nullable<decimal> BrTel { get; set; }
        public Nullable<int> Lokal { get; set; }
        public string VrstaEmail { get; set; }
        public string Email { get; set; }
        public byte[] FotoPecat { get; set; }
        public string Beleske { get; set; }
        public string KorisnikTip { get; set; }
        public string Korisnik { get; set; }
        public string UserEmail { get; set; }
    }
}
